### ISSUE TITLE
PDF Formatting on Download

### ISSUE THREAD

**Issue by tarahalwes** [dkapell/campaign-db#2]
Some character sheets have a line or two writing over eachother in the autogenerated PDF, at the top of pages after the first, making a skill or description partly illegible. Example ![image](https://github.com/user-attachments/assets/37705843-b9bb-4983-963c-614d7f212b99)

From https://mythboundlarp.com/character/227/pdf

**Comment by tarahalwes** [comment]
I suspect the sheets that don't have the legibility problem are still writing two lines on top of eachother but one of the lines just happens to be blank 

If it's not that then it's a mysterious Tara-only problem

**Comment by dkapell** [comment]
This was mostly resolved with Commit 508cf22
