### ISSUE TITLE
CP displayed on character sheet updates at unexpected times

### ISSUE THREAD

**Issue by tarahalwes** [dkapell/campaign-db#3]
Removing skills to trim down from 13 CP to 10CP, I removed a 3CP skill and the total didn't update on the page. Toggling between table pages and refreshing the web page didnt update it either. I deleted more things, saw 8CP when I expected 6, etc. I then thought to check the PDF download and even going back and forth got different values on the page (6) and the PDF (8)

![image](https://github.com/user-attachments/assets/c7465f7e-8a1c-42a7-bdf8-29fa73edb09e)

![image](https://github.com/user-attachments/assets/a810beb4-9b1e-4be0-b95f-35193421633a)

A little while later I reloaded the web page again and now it matches the pdf (8CP). 

Usability challenge for me while trying to tweak build spend. All of this is on mobile in Safari browser

**Comment by dkapell** [comment]
This was resolved with commit #7dd8f5e
